databases:
  - name: kiterwave
    databaseName: kiterwave
    user: kiterwave

services:
  - type: web
    name: kiterwave
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kiterwave
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false